live_config_reload = true

[font]
size = 12.5

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.italic]
family = "Iosevka NF"
style = "Regular"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
dimensions = {columns = 130, lines = 35}

[window.padding]
x = 5
y = 5

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[keyboard]
bindings = [
  { key = "v", mods = "Alt", action = "Paste"},
  { key = "c", mods = "Alt", action = "Copy"},
]

[colors.primary]
background = "#24283b"
foreground = "#a9b1d6"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#9699a8"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"
