[general]
live_config_reload = true
import = ["~/.config/alacritty/tokyo.toml"]

[font]
size = 20

[font.bold]
family = "Agave Nerd Font"
style = "Regular"

[font.italic]
family = "Agave Nerd Font"
style = "Regular"

[font.normal]
family = "Agave Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Agave Nerd Font"
style = "Regular"

# [font.bold]
# family = "Iosevka NF"
# style = "Regualar"

# [font.italic]
# family = "Iosevka NF"
# style = "Regular"

# [font.normal]
# family = "Iosevka NF"
# style = "Regular"

# [font.bold_italic]
# family = "Iosevka NF"
# style = "Regular"

# [font.bold]
# family = "Vitkovac H"
# style = "Regular"

# [font.italic]
# family = "Vitkovac H"
# style = "Regular"

# [font.normal]
# family = "Vitkovac H"
# style = "Regular"

# [font.bold_italic]
# family = "Vitkovac H"
# style = "Regular"


[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
dimensions = { columns = 130, lines = 35 }

[window.padding]
x = 15
y = 15
# x = 0
# y = 0
[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.1

[keyboard]
bindings = [
  { key = "v", mods = "Alt", action = "Paste" },
  { key = "c", mods = "Alt", action = "Copy" },
]
