[font]
size = 12

[font.bold]
family = "Agave Nerd Font"
style = "Regular"

[font.italic]
family = "Agave Nerd Font"
style = "Regular"

[font.normal]
family = "Agave Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Agave Nerd Font"
style = "Regular"

# [font.bold]
# family = "Iosevka NF"
# style = "Regular"

# [font.italic]
# family = "Iosevka NF"
# style = "Regular"

# [font.normal]
# family = "Iosevka NF"
# style = "Regular"

# [font.bold_italic]
# family = "Iosevka NF"
# style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
dimensions = {columns = 130, lines = 35}
# opacity = 0.9

[window.padding]
x = 15
y = 15

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.1

[keyboard]
bindings = [
  { key = "v", mods = "Alt", action = "Paste"},
  { key = "c", mods = "Alt", action = "Copy"},
]

[general]
live_config_reload = true
import = ["~/.config/alacritty/tokyo.toml"]
