live_config_reload = true

[font]
size = 14

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.italic]
family = "Iosevka NF"
style = "Regular"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
dimensions = {columns = 130, lines = 35}

[window.padding]
x = 5
y = 5

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[keyboard]
bindings = [
  { key = "v", mods = "Alt", action = "Paste"},
  { key = "c", mods = "Alt", action = "Copy"},
]

[colors.primary]
background = "0x0a0c10"
foreground = "0xf0f3f6"

[colors.cursor]
text = "0x0a0c10"
cursor = "0xf0f3f6"

[colors.normal]
black = "0x7a828e"
red = "0xff9492"
green = "0x26cd4d"
yellow = "0xf0b72f"
blue = "0x71b7ff"
magenta = "0xcb9eff"
cyan = "0x39c5cf"
white = "0xd9dee3"

[colors.bright]
black = "0x9ea7b3"
red = "0xffb1af"
green = "0x4ae168"
yellow = "0xf7c843"
blue = "0x91cbff"
magenta = "0xcb9eff"
cyan = "0x39c5cf"
white = "0xd9dee3"
