import = ["~/.config/alacritty/catppuccin_mocha.toml"]

live_config_reload = true

[font]
size = 17

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.italic]
family = "Iosevka NF"
style = "Regular"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
dimensions = {columns = 130, lines = 35}

[window.padding]
x = 20
y = 20

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[keyboard]
bindings = [
  { key = "v", mods = "Alt", action = "Paste"},
  { key = "c", mods = "Alt", action = "Copy"},
]

# [colors.primary]
# background = "0x1E1E1E"
# foreground = "0xD4D4D4"

# [colors.normal]
# black = "0x1E1E1E"
# red = "0xF44747"
# green = "0x608B4E"
# yellow = "0xD7BA7D"
# blue = "0x569CD6"
# magenta = "0xC586C0"
# cyan = "0x9CDCFE"
# white = "0xD4D4D4"
