live_config_reload = true

[font]
size = 14

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.italic]
family = "Iosevka NF"
style = "Regular"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
dimensions = {columns = 130, lines = 35}

[window.padding]
x = 10
y = 10

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[keyboard]
bindings = [
  { key = "v", mods = "Alt", action = "Paste"},
  { key = "c", mods = "Alt", action = "Copy"},
]

# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"

# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"

# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"

# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"

# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"

# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"

# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"

# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"

# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"

# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"

# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"

[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[colors.normal]
black = "0x2c2525"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[colors.bright]
black = "0x72696a"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"
