[font]
size = 10

[font.bold]
family = "JetbrainsMono NF"
style = "Regular"

[font.italic]
family = "JetbrainsMono NF"
style = "Regular"

[font.normal]
family = "JetbrainsMono NF"
style = "Regular"

[font.bold_italic]
family = "JetbrainsMono NF"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
dimensions = {columns = 130, lines = 35}
# opacity = 0.9

[window.padding]
x = 20
y = 20

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[keyboard]
bindings = [
  { key = "v", mods = "Alt", action = "Paste"},
  { key = "c", mods = "Alt", action = "Copy"},
]

[general]
live_config_reload = true
import = ["~/.config/alacritty/tokyo.toml"]
