import = ["~/.config/alacritty/everforest.toml"]

live_config_reload = true

[font]
size = 15

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.italic]
family = "Iosevka NF"
style = "Regular"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
dimensions = {columns = 130, lines = 35}

[window.padding]
x = 5
y = 5

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[keyboard]
bindings = [
  { key = "v", mods = "Alt", action = "Paste"},
  { key = "c", mods = "Alt", action = "Copy"},
]
